// <auto-generated />
namespace workshop_asp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class change_type_column : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_type_column));
        
        string IMigrationMetadata.Id
        {
            get { return "202005210716092_change_type_column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
