// <auto-generated />
namespace workshop_asp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class edit_colme_product_detail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edit_colme_product_detail));
        
        string IMigrationMetadata.Id
        {
            get { return "202005191708299_edit_colme_product_detail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
